### ISSUE TITLE
Invalid .pl and .cs translations

### ISSUE THREAD

**Issue by scaytrase** [ljesapps/moderation-translations#10]
Seems like these languages have more than two plural options (like russial language does). So plural form should be provided in for of

``` yml
translation.key: %count% яблоко|%count% яблока|%count% яблок|
```

where first form is for 1,21,101 etc number, second is for 2,3,4 item number and third is for all other options

**Comment by scaytrase** [comment]
.cc @Paranoidalny and @zorro5101 as authors of relevant translations

**Comment by vsinyavsky** [comment]
Гуглотранслейтом я это перевел. Пихай просто в продакшн, починить надо.

**Comment by vsinyavsky** [comment]
Чешский перевод я вообще удалил, т.к. нихрена никто не перевел

**Comment by vsinyavsky** [comment]
Испанский я тоже удалил.
